### ISSUE TITLE
Automate Tile generation using VISP

### ISSUE THREAD

**Issue by konradoo11** [aicell-lab/agent-lens#25]

**Comment by cccoolll** [comment]
Hi @hugokallander @konradoo11 As Wei mentioned before([see slack link](https://aicell-lab.slack.com/archives/C0634MRH7KM/p1731431315758169)), the tiles should be generated using 'OME-NGFF'. I am working on that, please see my [pull request](https://github.com/aicell-lab/squid-control/pull/2).
