### ISSUE TITLE
Read the zarr image & provide tiles for the OpenLayers

### ISSUE THREAD

**Issue by konradoo11** [aicell-lab/agent-lens#8]
Try to read the zarr image and then provide the tiles for the openlayers to be able to display in the webpage.

**Comment by oeway** [comment]
Where is the PR in review?

**Comment by cccoolll** [comment]
The pull request is here, the issue should belong to the 'squid-control' repo. Maybe I should close this and create a new issue, and link to the PR.
https://github.com/aicell-lab/squid-control/pull/2

**Comment by cccoolll** [comment]
@oeway @konradoo11 Since these features are developed in 'squid-control' repo, I'm going to close this item and make a new one with PR linked

**Comment by oeway** [comment]
That's fine. You can always paste a link in the description for quick reference.
